---
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: longhorn
  namespace: fleet-default
spec:
  repo: https://github.com/drdrunkenbear/longhorn-crd
  branch: main
  paths:
  - helm/longhorn
  targets:
  - clusterSelector: {}
---
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: longhorn-crd
  namespace: fleet-default
spec:
  repo: https://github.com/drdrunkenbear/longhorn-crd
  branch: main
  paths:
  - helm/longhorn-crd
  targets:
  - clusterSelector: {}
